/**
 * @xrmforge/typegen - Action/Function Generator
 *
 * Generates TypeScript files for type-safe Custom API execution:
 * - .d.ts: Parameter/Response interfaces and executor types
 * - .ts: Runtime modules that import factory functions from @xrmforge/typegen
 *
 * Input: CustomApiTypeInfo[] (from fixture JSON or live Dataverse query)
 * Output: Grouped by entity (bound) or "global" (unbound)
 *
 * @example Generated output for markant_NormalizePhone (unbound action):
 * ```typescript
 * // global.d.ts
 * declare namespace XrmForge.Actions {
 *   interface NormalizePhoneParams { Input: string; AllowSuspicious?: boolean; }
 *   interface NormalizePhoneResult { Normalized: string; Status: number; Message: string; }
 * }
 *
 * // global.ts
 * import { createUnboundAction } from '@xrmforge/typegen';
 * export const NormalizePhone = createUnboundAction<...>('markant_NormalizePhone', { ... });
 * ```
 */

import type {
  CustomApiTypeInfo,
  CustomApiRequestParameter,
  CustomApiResponseProperty,
} from '../metadata/custom-api-types.js';
import { mapCustomApiParameterType, CustomApiBindingType } from '../metadata/custom-api-types.js';
import { toPascalCase } from './type-mapping.js';

// ─── Options ────────────────────────────────────────────────────────────────

/** Options for action/function generation */
export interface ActionGeneratorOptions {
  /** Import path for @xrmforge/typegen (default: "@xrmforge/typegen") */
  importPath?: string;
  /** Namespace for generated types (default: "XrmForge.Actions" / "XrmForge.Functions") */
  actionsNamespace?: string;
  functionsNamespace?: string;
}

// ─── Naming ─────────────────────────────────────────────────────────────────

/**
 * Derive a clean PascalCase name from the Custom API uniquename.
 * Removes common prefixes like "markant_", "dev1_" etc.
 *
 * Examples:
 * - "markant_NormalizePhone" -> "NormalizePhone"
 * - "markant_winquote" -> "WinQuote"
 * - "WhoAmI" -> "WhoAmI"
 */
function deriveActionName(uniquename: string): string {
  // Entferne Publisher-Prefix (alles vor und inklusive dem ersten Unterstrich)
  const withoutPrefix = uniquename.includes('_')
    ? uniquename.substring(uniquename.indexOf('_') + 1)
    : uniquename;
  return toPascalCase(withoutPrefix);
}

// ─── Interface Generation ───────────────────────────────────────────────────

function generateParamsInterface(
  name: string,
  params: CustomApiRequestParameter[],
): string {
  if (params.length === 0) return '';

  const lines: string[] = [];
  lines.push(`  interface ${name}Params {`);

  for (const param of params) {
    const mapped = mapCustomApiParameterType(param.type, param.logicalentityname);
    const optional = param.isoptional ? '?' : '';
    if (param.description) {
      lines.push(`    /** ${param.description} */`);
    }
    lines.push(`    ${param.uniquename}${optional}: ${mapped.tsType};`);
  }

  lines.push('  }');
  return lines.join('\n');
}

function generateResultInterface(
  name: string,
  props: CustomApiResponseProperty[],
): string {
  if (props.length === 0) return '';

  const lines: string[] = [];
  lines.push(`  interface ${name}Result {`);

  for (const prop of props) {
    const mapped = mapCustomApiParameterType(prop.type, prop.logicalentityname);
    if (prop.description) {
      lines.push(`    /** ${prop.description} */`);
    }
    lines.push(`    ${prop.uniquename}: ${mapped.tsType};`);
  }

  lines.push('  }');
  return lines.join('\n');
}

// ─── Declaration (.d.ts) Generation ─────────────────────────────────────────

/**
 * Generate .d.ts content for a group of Custom APIs.
 *
 * @param apis - Custom APIs to generate (all in the same group: same entity or all global)
 * @param isFunction - true for functions namespace, false for actions
 * @param entityName - Entity name for bound APIs, undefined for global
 * @param options - Generator options
 */
export function generateActionDeclarations(
  apis: CustomApiTypeInfo[],
  isFunction: boolean,
  entityName?: string,
  options: ActionGeneratorOptions = {},
): string {
  const baseNamespace = isFunction
    ? (options.functionsNamespace || 'XrmForge.Functions')
    : (options.actionsNamespace || 'XrmForge.Actions');

  const namespace = entityName
    ? `${baseNamespace}.${toPascalCase(entityName)}`
    : baseNamespace;

  const lines: string[] = [];
  lines.push('// Auto-generated by @xrmforge/typegen - DO NOT EDIT');
  lines.push('');
  lines.push(`declare namespace ${namespace} {`);

  for (const apiInfo of apis) {
    const name = deriveActionName(apiInfo.api.uniquename);
    const hasParams = apiInfo.requestParameters.length > 0;
    const hasResult = apiInfo.responseProperties.length > 0;

    lines.push('');

    // JSDoc
    const description = apiInfo.api.description || apiInfo.api.displayname || apiInfo.api.uniquename;
    lines.push(`  /** ${description} (${apiInfo.api.uniquename}) */`);

    // Params interface
    if (hasParams) {
      lines.push(generateParamsInterface(name, apiInfo.requestParameters));
      lines.push('');
    }

    // Result interface
    if (hasResult) {
      lines.push(generateResultInterface(name, apiInfo.responseProperties));
      lines.push('');
    }

    // Executor type (so the .ts export is typed)
    const importFrom = options.importPath || '@xrmforge/typegen';
    if (apiInfo.api.bindingtype === CustomApiBindingType.Global) {
      if (hasParams && hasResult) {
        lines.push(`  const ${name}: import('${importFrom}').UnboundActionWithParamsExecutor<${name}Params, ${name}Result>;`);
      } else if (hasParams) {
        lines.push(`  const ${name}: import('${importFrom}').UnboundActionWithParamsExecutor<${name}Params, void>;`);
      } else {
        lines.push(`  const ${name}: import('${importFrom}').UnboundActionExecutor;`);
      }
    } else {
      if (hasParams) {
        lines.push(`  const ${name}: import('${importFrom}').BoundActionWithParamsExecutor<${name}Params>;`);
      } else {
        lines.push(`  const ${name}: import('${importFrom}').BoundActionExecutor;`);
      }
    }
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

// ─── Runtime Module (.ts) Generation ────────────────────────────────────────

/**
 * Generate .ts content with runtime executors for a group of Custom APIs.
 *
 * @param apis - Custom APIs to generate
 * @param isFunction - true for functions, false for actions
 * @param options - Generator options
 */
export function generateActionModule(
  apis: CustomApiTypeInfo[],
  isFunction: boolean,
  options: ActionGeneratorOptions = {},
): string {
  const importPath = options.importPath || '@xrmforge/typegen';
  const lines: string[] = [];

  lines.push('// Auto-generated by @xrmforge/typegen - DO NOT EDIT');
  lines.push('');

  // Sammle benoetigte Imports
  const imports = new Set<string>();
  for (const apiInfo of apis) {
    if (apiInfo.api.bindingtype === CustomApiBindingType.Global) {
      if (isFunction) {
        imports.add('createUnboundFunction');
      } else {
        imports.add('createUnboundAction');
      }
    } else {
      if (isFunction) {
        imports.add('createBoundFunction');
      } else {
        imports.add('createBoundAction');
      }
    }
  }

  lines.push(`import { ${[...imports].sort().join(', ')} } from '${importPath}';`);
  lines.push('');

  for (const apiInfo of apis) {
    const name = deriveActionName(apiInfo.api.uniquename);
    const hasParams = apiInfo.requestParameters.length > 0;

    // JSDoc
    const description = apiInfo.api.description || apiInfo.api.displayname || apiInfo.api.uniquename;
    lines.push(`/** ${description} */`);

    if (apiInfo.api.bindingtype === CustomApiBindingType.Global) {
      // Unbound
      if (isFunction) {
        lines.push(`export const ${name} = createUnboundFunction('${apiInfo.api.uniquename}');`);
      } else if (hasParams) {
        // Parameter-Metadata-Map erzeugen
        const paramMeta = generateParameterMetaMap(apiInfo.requestParameters);
        lines.push(`export const ${name} = createUnboundAction('${apiInfo.api.uniquename}', ${paramMeta});`);
      } else {
        lines.push(`export const ${name} = createUnboundAction('${apiInfo.api.uniquename}');`);
      }
    } else {
      // Bound
      const entity = apiInfo.api.boundentitylogicalname!;
      if (isFunction) {
        lines.push(`export const ${name} = createBoundFunction('${apiInfo.api.uniquename}', '${entity}');`);
      } else if (hasParams) {
        const paramMeta = generateParameterMetaMap(apiInfo.requestParameters);
        lines.push(`export const ${name} = createBoundAction('${apiInfo.api.uniquename}', '${entity}', ${paramMeta});`);
      } else {
        lines.push(`export const ${name} = createBoundAction('${apiInfo.api.uniquename}', '${entity}');`);
      }
    }

    lines.push('');
  }

  return lines.join('\n');
}

// ─── Parameter Metadata Map ─────────────────────────────────────────────────

function generateParameterMetaMap(params: CustomApiRequestParameter[]): string {
  const entries: string[] = [];
  for (const param of params) {
    const mapped = mapCustomApiParameterType(param.type, param.logicalentityname);
    entries.push(
      `  ${param.uniquename}: { typeName: '${mapped.typeName}', structuralProperty: ${mapped.structuralProperty} }`,
    );
  }
  return `{\n${entries.join(',\n')},\n}`;
}

// ─── Grouping Helper ────────────────────────────────────────────────────────

/** Group result: key is entity logical name or "global" for unbound */
export interface GroupedCustomApis {
  actions: Map<string, CustomApiTypeInfo[]>;
  functions: Map<string, CustomApiTypeInfo[]>;
}

/**
 * Group Custom APIs by entity (bound) or "global" (unbound),
 * and separate actions from functions.
 */
export function groupCustomApis(apis: CustomApiTypeInfo[]): GroupedCustomApis {
  const actions = new Map<string, CustomApiTypeInfo[]>();
  const functions = new Map<string, CustomApiTypeInfo[]>();

  for (const api of apis) {
    const target = api.api.isfunction ? functions : actions;
    const key = api.api.bindingtype === CustomApiBindingType.Global
      ? 'global'
      : (api.api.boundentitylogicalname || 'global');

    if (!target.has(key)) {
      target.set(key, []);
    }
    target.get(key)!.push(api);
  }

  return { actions, functions };
}
