/**
 * @xrmforge/formhelpers - TypedForm Proxy
 *
 * Creates a proxy around Xrm.FormContext that allows direct property access
 * to form fields. Instead of formContext.getAttribute("name").setValue("X"),
 * write form.name.setValue("X").
 *
 * @example
 * ```typescript
 * import { typedForm } from '@xrmforge/formhelpers';
 *
 * type LeadForm = XrmForge.Forms.Lead.LeadMarkantLeadForm;
 *
 * const form = typedForm<LeadForm>(formContext);
 * form.companyname.setValue("Contoso");       // StringAttribute
 * form.parentaccountid.getValue();             // LookupValue[] | null
 * form.$context.ui.setFormNotification(...);   // Full FormContext access
 * form.$control("companyname").setDisabled(true);
 * ```
 */

/**
 * Extracts the Fields union type from a generated Form interface.
 * Works with the XrmForge-generated pattern:
 *   getAttribute<K extends Fields>(name: K): AttrMap[K]
 *
 * For overloaded getAttribute, TypeScript resolves to the last overload.
 * Our generated interfaces have the generic overload first, so we use
 * a mapped approach with the AttrMap instead.
 */
export type FormFields<TForm> = TForm extends {
  getAttribute(name: infer K): unknown;
} ? K extends string ? K : string : string;

/**
 * TypedForm: proxy type that maps field names to their attribute types.
 *
 * Since extracting Fields + AttrMap from overloaded getAttribute is unreliable
 * in TypeScript, we use a two-parameter approach internally but expose a
 * single-parameter API via a helper type generated by typegen (FormTypedInfo).
 *
 * For v0.1.0 we support both signatures:
 *   typedForm<TForm>(fc)                    -- works when TForm has proper generic getAttribute
 *   typedForm<TForm, TFields, TAttrMap>(fc) -- explicit, always works
 */
export type TypedForm<
  _TForm,
  TFields extends string = string,
  TAttrMap extends Record<string, Xrm.Attributes.Attribute> = Record<string, Xrm.Attributes.Attribute>,
> = {
  readonly [K in TFields]: K extends keyof TAttrMap
    ? TAttrMap[K]
    : Xrm.Attributes.Attribute;
} & {
  /** Access the underlying FormContext for ui, data, tabs, etc. */
  readonly $context: Xrm.FormContext;
  /** Access a control by field name */
  $control(name: TFields): Xrm.Controls.Control;
};

/**
 * Create a typed form proxy around a FormContext.
 *
 * The proxy intercepts property access and delegates to getAttribute().
 * Special properties $context and $control provide access to the full
 * FormContext and controls respectively.
 *
 * @param formContext - The Xrm.FormContext from executionContext.getFormContext()
 * @returns A proxy with direct property access to form fields
 */
export function typedForm<
  TForm,
  TFields extends string = string,
  TAttrMap extends Record<string, Xrm.Attributes.Attribute> = Record<string, Xrm.Attributes.Attribute>,
>(formContext: Xrm.FormContext): TypedForm<TForm, TFields, TAttrMap> {
  return new Proxy(formContext as unknown as TypedForm<TForm, TFields, TAttrMap>, {
    get(_target, prop) {
      // Symbols and non-string keys: delegate to formContext
      if (typeof prop !== 'string') {
        return (formContext as unknown as Record<symbol, unknown>)[prop];
      }
      if (prop === '$context') return formContext;
      if (prop === '$control') {
        return (name: string) => formContext.getControl(name);
      }
      // Try getAttribute first (form field access)
      const attr = formContext.getAttribute(prop);
      if (attr) return attr;
      // Fallback to FormContext properties (data, ui, etc.)
      return (formContext as unknown as Record<string, unknown>)[prop];
    },

    set(_target, prop, _value) {
      throw new TypeError(
        `Cannot assign to '${String(prop)}'. Use form.${String(prop)}.setValue() instead.`,
      );
    },

    has(_target, prop) {
      if (typeof prop !== 'string') return false;
      if (prop === '$context' || prop === '$control') return true;
      return formContext.getAttribute(prop) !== null;
    },
  });
}
