/**
 * @xrmforge/typegen - File Writer
 *
 * Writes generated .ts files to disk with proper directory structure:
 *
 * outputDir/
 *   entities/
 *     account.ts
 *     contact.ts
 *   optionsets/
 *     account.ts          (all OptionSets for one entity)
 *   forms/
 *     account.ts          (all form interfaces for one entity)
 *   fields/
 *     account.ts          (FieldsEnum + NavigationProperties)
 *   index.ts              (barrel re-export file)
 */

import { mkdir, writeFile, readFile, unlink } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import type { GeneratedFile } from './types.js';

/**
 * Write a generated file to disk, creating directories as needed.
 *
 * @param outputDir - Base output directory
 * @param file - Generated file to write
 * @returns true if file was written (content changed), false if unchanged
 */
export async function writeGeneratedFile(outputDir: string, file: GeneratedFile): Promise<boolean> {
  const absolutePath = join(outputDir, file.relativePath);

  // Check if file already exists with same content (avoid unnecessary writes)
  try {
    const existing = await readFile(absolutePath, 'utf-8');
    if (existing === file.content) {
      return false; // No change
    }
  } catch {
    // File doesn't exist yet, proceed with write
  }

  // Ensure directory exists
  await mkdir(dirname(absolutePath), { recursive: true });

  // Write file
  await writeFile(absolutePath, file.content, 'utf-8');

  return true;
}

/** Result of writing a batch of files */
export interface WriteResult {
  /** Number of files successfully written (content changed) */
  written: number;
  /** Number of files unchanged (already up to date) */
  unchanged: number;
  /** Warnings for files that could not be written (non-fatal) */
  warnings: string[];
}

/**
 * Write all generated files to disk.
 * A single file write failure does NOT abort the entire batch.
 * Errors are collected as warnings so the remaining files are still written.
 *
 * @param outputDir - Base output directory
 * @param files - Array of generated files
 * @returns WriteResult with counts and warnings
 */
export async function writeAllFiles(outputDir: string, files: GeneratedFile[]): Promise<WriteResult> {
  const result: WriteResult = { written: 0, unchanged: 0, warnings: [] };

  for (const file of files) {
    try {
      const changed = await writeGeneratedFile(outputDir, file);
      if (changed) {
        result.written++;
      } else {
        result.unchanged++;
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      result.warnings.push(`Konnte ${file.relativePath} nicht schreiben: ${message}`);
    }
  }

  return result;
}

/**
 * Delete orphaned .d.ts files for entities that were removed from Dataverse.
 * Removes entity, optionset, and form files for the given entity names.
 *
 * @param outputDir - Base output directory
 * @param deletedEntityNames - Entity logical names whose files should be removed
 * @returns Number of files deleted
 */
export async function deleteOrphanedFiles(outputDir: string, deletedEntityNames: string[]): Promise<number> {
  let deleted = 0;
  const subdirs = ['entities', 'optionsets', 'forms', 'fields'];

  for (const entityName of deletedEntityNames) {
    for (const subdir of subdirs) {
      const filePath = join(outputDir, subdir, `${entityName}.ts`);
      try {
        await unlink(filePath);
        deleted++;
      } catch (error: unknown) {
        // File might not exist (entity had no forms/optionsets), that's fine
        if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
          throw error;
        }
      }
    }
  }

  return deleted;
}

/** File header for generated files */
const GENERATED_HEADER = `// ──────────────────────────────────────────────────────────────────────────────
// This file was generated by @xrmforge/typegen. Do not edit manually.
// Re-run 'xrmforge generate' to update.
// ──────────────────────────────────────────────────────────────────────────────

`;

/**
 * Wrap generated content with the standard header.
 */
export function addGeneratedHeader(content: string): string {
  return GENERATED_HEADER + content;
}

/**
 * Convert a relative .ts path to an ESM import specifier with .js extension.
 * TypeScript ESM convention: import specifiers use .js, resolved to .ts at compile time.
 *
 * @example toImportSpecifier('entities/account.ts') => './entities/account.js'
 */
function toImportSpecifier(relativePath: string): string {
  const withoutExt = relativePath.replace(/\.ts$/, '');
  return `./${withoutExt}.js`;
}

/**
 * Generate a barrel index.ts that re-exports all generated files.
 *
 * @param files - All generated files
 * @returns Content for index.ts
 */
export function generateBarrelIndex(files: GeneratedFile[]): string {
  const lines: string[] = [GENERATED_HEADER];

  // Group by type for organized output
  const entities = files.filter((f) => f.type === 'entity');
  const optionsets = files.filter((f) => f.type === 'optionset');
  const forms = files.filter((f) => f.type === 'form');
  const fields = files.filter((f) => f.type === 'fields');
  const actions = files.filter((f) => f.type === 'action');

  if (entities.length > 0) {
    lines.push('// Entity Interfaces');
    for (const f of entities) {
      lines.push(`export * from '${toImportSpecifier(f.relativePath)}';`);
    }
    lines.push('');
  }

  if (optionsets.length > 0) {
    lines.push('// OptionSet Enums');
    for (const f of optionsets) {
      lines.push(`export * from '${toImportSpecifier(f.relativePath)}';`);
    }
    lines.push('');
  }

  if (forms.length > 0) {
    lines.push('// Form Interfaces');
    for (const f of forms) {
      lines.push(`export * from '${toImportSpecifier(f.relativePath)}';`);
    }
    lines.push('');
  }

  if (fields.length > 0) {
    lines.push('// Entity Fields & Navigation Properties');
    for (const f of fields) {
      lines.push(`export * from '${toImportSpecifier(f.relativePath)}';`);
    }
    lines.push('');
  }

  if (actions.length > 0) {
    lines.push('// Custom API Actions & Functions');
    for (const f of actions) {
      lines.push(`export * from '${toImportSpecifier(f.relativePath)}';`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
