/**
 * @xrmforge/typegen - File Writer
 *
 * Writes generated .d.ts files to disk with proper directory structure:
 *
 * outputDir/
 *   entities/
 *     account.d.ts
 *     contact.d.ts
 *   optionsets/
 *     account.d.ts        (all OptionSets for one entity)
 *   forms/
 *     account.d.ts        (all form interfaces for one entity)
 *   index.d.ts            (barrel reference file)
 */

import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import type { GeneratedFile } from './types.js';

/**
 * Write a generated file to disk, creating directories as needed.
 *
 * @param outputDir - Base output directory
 * @param file - Generated file to write
 * @returns true if file was written (content changed), false if unchanged
 */
export async function writeGeneratedFile(outputDir: string, file: GeneratedFile): Promise<boolean> {
  const absolutePath = join(outputDir, file.relativePath);

  // Check if file already exists with same content (avoid unnecessary writes)
  try {
    const existing = await readFile(absolutePath, 'utf-8');
    if (existing === file.content) {
      return false; // No change
    }
  } catch {
    // File doesn't exist yet, proceed with write
  }

  // Ensure directory exists
  await mkdir(dirname(absolutePath), { recursive: true });

  // Write file
  await writeFile(absolutePath, file.content, 'utf-8');

  return true;
}

/**
 * Write all generated files to disk.
 *
 * @param outputDir - Base output directory
 * @param files - Array of generated files
 * @returns Number of files actually written (changed)
 */
export async function writeAllFiles(outputDir: string, files: GeneratedFile[]): Promise<number> {
  let written = 0;

  for (const file of files) {
    const changed = await writeGeneratedFile(outputDir, file);
    if (changed) written++;
  }

  return written;
}

/** File header for generated .d.ts files */
const GENERATED_HEADER = `// ──────────────────────────────────────────────────────────────────────────────
// This file was generated by @xrmforge/typegen. Do not edit manually.
// Re-run 'xrmforge generate' to update.
// ──────────────────────────────────────────────────────────────────────────────

`;

/**
 * Wrap generated content with the standard header.
 */
export function addGeneratedHeader(content: string): string {
  return GENERATED_HEADER + content;
}

/**
 * Generate a barrel index.d.ts that references all generated files.
 *
 * @param files - All generated files
 * @returns Content for index.d.ts
 */
export function generateBarrelIndex(files: GeneratedFile[]): string {
  const lines: string[] = [GENERATED_HEADER];

  // Group by type for organized output
  const entities = files.filter((f) => f.type === 'entity');
  const optionsets = files.filter((f) => f.type === 'optionset');
  const forms = files.filter((f) => f.type === 'form');

  if (entities.length > 0) {
    lines.push('// Entity Interfaces');
    for (const f of entities) {
      lines.push(`/// <reference path="${f.relativePath}" />`);
    }
    lines.push('');
  }

  if (optionsets.length > 0) {
    lines.push('// OptionSet Enums');
    for (const f of optionsets) {
      lines.push(`/// <reference path="${f.relativePath}" />`);
    }
    lines.push('');
  }

  if (forms.length > 0) {
    lines.push('// Form Interfaces');
    for (const f of forms) {
      lines.push(`/// <reference path="${f.relativePath}" />`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
