import { describe, it, expect } from 'vitest';
import {
  generateActionDeclarations,
  generateActionModule,
  groupCustomApis,
} from '../src/generators/action-generator.js';
import type { CustomApiTypeInfo } from '../src/metadata/custom-api-types.js';

// ─── Test Fixtures ──────────────────────────────────────────────────────────

const unboundActionNoParams: CustomApiTypeInfo = {
  api: {
    uniquename: 'markant_SimpleAction',
    bindingtype: 0,
    isfunction: false,
    boundentitylogicalname: null,
    displayname: 'Simple Action',
    description: 'Einfache Action ohne Parameter',
  },
  requestParameters: [],
  responseProperties: [],
};

const unboundActionWithParams: CustomApiTypeInfo = {
  api: {
    uniquename: 'markant_NormalizePhone',
    bindingtype: 0,
    isfunction: false,
    boundentitylogicalname: null,
    displayname: 'Normalize Phone',
    description: 'Normalisiert Telefonnummern',
  },
  requestParameters: [
    { uniquename: 'Input', type: 10, isoptional: false, description: 'Telefonnummer' },
    { uniquename: 'AllowSuspicious', type: 0, isoptional: true },
  ],
  responseProperties: [
    { uniquename: 'Normalized', type: 10 },
    { uniquename: 'Status', type: 7 },
    { uniquename: 'Message', type: 10 },
  ],
};

const boundAction: CustomApiTypeInfo = {
  api: {
    uniquename: 'markant_winquote',
    bindingtype: 1,
    isfunction: false,
    boundentitylogicalname: 'quote',
    displayname: 'Win Quote',
  },
  requestParameters: [],
  responseProperties: [],
};

const boundActionWithResult: CustomApiTypeInfo = {
  api: {
    uniquename: 'markant_ValidateQuote',
    bindingtype: 1,
    isfunction: false,
    boundentitylogicalname: 'quote',
    displayname: 'Validate Quote',
    description: 'Validates a quote',
  },
  requestParameters: [],
  responseProperties: [
    { uniquename: 'IsValid', type: 0 },
    { uniquename: 'Message', type: 10 },
  ],
};

const boundActionWithParamsAndResult: CustomApiTypeInfo = {
  api: {
    uniquename: 'markant_CloneQuote',
    bindingtype: 1,
    isfunction: false,
    boundentitylogicalname: 'quote',
    displayname: 'Clone Quote',
    description: 'Clones a quote with options',
  },
  requestParameters: [
    { uniquename: 'IncludeProducts', type: 0, isoptional: true },
  ],
  responseProperties: [
    { uniquename: 'ClonedQuoteId', type: 12 },
  ],
};

const unboundActionWithResultOnly: CustomApiTypeInfo = {
  api: {
    uniquename: 'markant_GetServerTime',
    bindingtype: 0,
    isfunction: false,
    boundentitylogicalname: null,
    displayname: 'Get Server Time',
    description: 'Returns current server time',
  },
  requestParameters: [],
  responseProperties: [
    { uniquename: 'Timestamp', type: 10 },
  ],
};

const unboundFunction: CustomApiTypeInfo = {
  api: {
    uniquename: 'WhoAmI',
    bindingtype: 0,
    isfunction: true,
    boundentitylogicalname: null,
    displayname: 'Who Am I',
  },
  requestParameters: [],
  responseProperties: [
    { uniquename: 'UserId', type: 12 },
    { uniquename: 'BusinessUnitId', type: 12 },
    { uniquename: 'OrganizationId', type: 12 },
  ],
};

// ─── Declaration Generation ─────────────────────────────────────────────────

describe('generateActionDeclarations', () => {
  it('should generate declaration for unbound action without params', () => {
    const output = generateActionDeclarations([unboundActionNoParams], false);
    expect(output).not.toContain('declare namespace');
    expect(output).toContain('SimpleAction');
    expect(output).not.toContain('Params');
  });

  it('should generate params and result interfaces', () => {
    const output = generateActionDeclarations([unboundActionWithParams], false);
    expect(output).toContain('export type NormalizePhoneParams');
    expect(output).toContain('Input: string');
    expect(output).toContain('AllowSuspicious?: boolean');
    expect(output).toContain('export type NormalizePhoneResult');
    expect(output).toContain('Normalized: string');
    expect(output).toContain('Status: number');
    expect(output).toContain('Message: string');
  });

  it('should generate bound action declarations', () => {
    const output = generateActionDeclarations([boundAction], false, 'quote');
    expect(output).not.toContain('declare namespace');
    expect(output).toContain('markant_winquote'); // uniquename appears in JSDoc
  });

  it('should generate function declarations without namespace', () => {
    const output = generateActionDeclarations([unboundFunction], true);
    expect(output).not.toContain('declare namespace');
    expect(output).toContain('export type WhoAmIResult');
    expect(output).toContain('UserId: string');
    expect(output).toContain('BusinessUnitId: string');
  });

  it('should include auto-generated header', () => {
    const output = generateActionDeclarations([unboundActionNoParams], false);
    expect(output).toContain('Auto-generated by @xrmforge/typegen');
    expect(output).toContain('DO NOT EDIT');
  });

  it('should strip publisher prefix from interface names', () => {
    const output = generateActionDeclarations([unboundActionWithParams], false);
    expect(output).toContain('NormalizePhoneParams');
    // Der uniquename erscheint im JSDoc-Kommentar (gewollt, als Referenz)
    expect(output).toContain('(markant_NormalizePhone)');
  });

  it('should mark optional params with ?', () => {
    const output = generateActionDeclarations([unboundActionWithParams], false);
    expect(output).toContain('AllowSuspicious?: boolean');
    expect(output).toMatch(/Input[^?]*: string/);
  });
});

// ─── Module Generation ──────────────────────────────────────────────────────

describe('generateActionModule', () => {
  it('should generate import statement', () => {
    const output = generateActionModule([unboundActionNoParams], false);
    expect(output).toContain("import { createUnboundAction } from '@xrmforge/helpers'");
  });

  it('should generate executor for unbound action without params', () => {
    const output = generateActionModule([unboundActionNoParams], false);
    expect(output).toContain("export const SimpleAction = createUnboundAction('markant_SimpleAction')");
  });

  it('should generate executor with typed params and result', () => {
    const output = generateActionModule([unboundActionWithParams], false);
    expect(output).toContain("export const NormalizePhone = createUnboundAction<NormalizePhoneParams, NormalizePhoneResult>('markant_NormalizePhone',");
    expect(output).toContain("Input: { typeName: 'Edm.String', structuralProperty: 1 }");
    expect(output).toContain("AllowSuspicious: { typeName: 'Edm.Boolean', structuralProperty: 1 }");
  });

  it('should generate bound action executor', () => {
    const output = generateActionModule([boundAction], false);
    expect(output).toContain("import { createBoundAction } from '@xrmforge/helpers'");
    expect(output).toContain("export const Winquote = createBoundAction('markant_winquote', 'quote')");
  });

  it('should generate unbound function executor with result type', () => {
    const output = generateActionModule([unboundFunction], true);
    expect(output).toContain("import { createUnboundFunction } from '@xrmforge/helpers'");
    expect(output).toContain("export const WhoAmI = createUnboundFunction<WhoAmIResult>('WhoAmI')");
  });

  it('should generate bound action with result type only', () => {
    const output = generateActionModule([boundActionWithResult], false);
    expect(output).toContain("export const ValidateQuote = createBoundAction<ValidateQuoteResult>('markant_ValidateQuote', 'quote')");
    expect(output).toContain('export type ValidateQuoteResult');
    expect(output).not.toContain('ValidateQuoteParams');
  });

  it('should generate bound action with params and result types', () => {
    const output = generateActionModule([boundActionWithParamsAndResult], false);
    expect(output).toContain("export const CloneQuote = createBoundAction<CloneQuoteParams, CloneQuoteResult>('markant_CloneQuote', 'quote',");
    expect(output).toContain('export type CloneQuoteParams');
    expect(output).toContain('export type CloneQuoteResult');
  });

  it('should generate unbound action with result type only (no params)', () => {
    const output = generateActionModule([unboundActionWithResultOnly], false);
    expect(output).toContain("export const GetServerTime = createUnboundAction<GetServerTimeResult>('markant_GetServerTime')");
    expect(output).toContain('export type GetServerTimeResult');
    expect(output).not.toContain('GetServerTimeParams');
  });

  it('should use custom import path', () => {
    const output = generateActionModule([unboundActionNoParams], false, {
      importPath: '../../lib/typegen',
    });
    expect(output).toContain("from '../../lib/typegen'");
  });

  it('should include JSDoc with description', () => {
    const output = generateActionModule([unboundActionWithParams], false);
    expect(output).toContain('/** Normalisiert Telefonnummern (markant_NormalizePhone) */');
  });
});

// ─── Grouping ───────────────────────────────────────────────────────────────

describe('groupCustomApis', () => {
  it('should separate actions and functions', () => {
    const grouped = groupCustomApis([unboundActionNoParams, unboundFunction]);
    expect(grouped.actions.size).toBe(1);
    expect(grouped.functions.size).toBe(1);
    expect(grouped.actions.get('global')!.length).toBe(1);
    expect(grouped.functions.get('global')!.length).toBe(1);
  });

  it('should group bound actions by entity', () => {
    const grouped = groupCustomApis([boundAction, unboundActionNoParams]);
    expect(grouped.actions.has('quote')).toBe(true);
    expect(grouped.actions.has('global')).toBe(true);
    expect(grouped.actions.get('quote')!.length).toBe(1);
  });

  it('should handle empty input', () => {
    const grouped = groupCustomApis([]);
    expect(grouped.actions.size).toBe(0);
    expect(grouped.functions.size).toBe(0);
  });

  it('should group multiple unbound actions together', () => {
    const grouped = groupCustomApis([
      unboundActionNoParams,
      unboundActionWithParams,
    ]);
    expect(grouped.actions.get('global')!.length).toBe(2);
  });
});
