/**
 * @xrmforge/helpers - TypedForm Proxy
 *
 * Creates a proxy around Xrm.FormContext that allows direct property access
 * to form fields. Instead of `form.getAttribute("name").setValue("X")`,
 * write `form.name.setValue("X")`.
 *
 * Works with generated form types from @xrmforge/typegen. Since v0.9.2,
 * typegen generates a `FormTypeInfo` interface per form that bundles
 * Fields, AttributeMap, and ControlMap for reliable type extraction.
 *
 * @example
 * ```typescript
 * import { typedForm } from '@xrmforge/helpers';
 * import type { AccountLMFirmaFormTypeInfo } from '../../generated/forms/account.js';
 *
 * const form = typedForm<AccountLMFirmaFormTypeInfo>(ctx.getFormContext());
 * form.name.getValue();           // string | null (typed)
 * form.revenue.setValue(150000);   // NumberAttribute (typed)
 * form.$context.ui.tabs.get(...); // Full FormContext access
 * form.controls.name;             // Control access (typed)
 * form.$unsafe('off_form_field');  // Access fields not on the form
 * ```
 */

// ─── FormTypeInfo Protocol ───────────────────────────────────────────────────

/**
 * Protocol interface generated by typegen for each form.
 * Bundles Fields, AttributeMap, and ControlMap so typedForm can extract
 * them reliably without fragile Conditional Type inference on overloads.
 *
 * Generated as: `export interface MyFormTypeInfo { fields: ...; attributes: ...; controls: ...; form: ...; }`
 */
export interface FormTypeInfoProtocol {
  fields: string;
  attributes: Record<string, Xrm.Attributes.Attribute>;
  controls: Record<string, Xrm.Controls.Control>;
  form: object;
}

// ─── Type Extraction ─────────────────────────────────────────────────────────

/**
 * Extract Fields from a Form interface.
 *
 * Strategy: Check if TForm has a companion TypeInfo interface (generated by
 * typegen >= 0.9.2). If so, extract fields directly. Otherwise, fall back
 * to Conditional Type inference on getAttribute (works in same compilation
 * unit but may fail across package boundaries in TS 5.9+).
 */
/**
 * Type extraction uses duck typing: if TForm has a `fields` property,
 * it's a TypeInfo interface (from typegen >= 0.10.0). Otherwise, fall
 * back to Conditional Type inference on getAttribute overloads.
 *
 * Duck typing (`TForm extends { fields: infer F }`) is more robust than
 * matching against FormTypeInfoProtocol because it doesn't require
 * structural compatibility of attributes/controls/form across packages.
 */
type ExtractFields<TForm> =
  TForm extends { fields: infer F extends string } ? F :
  TForm extends { getAttribute<K extends infer F>(name: K): unknown }
    ? F extends string ? F : never
    : never;

type ExtractAttributeMap<TForm, TFields extends string> =
  TForm extends { attributes: infer A extends Record<string, Xrm.Attributes.Attribute> } ? A :
  { [K in TFields]: TForm extends { getAttribute(name: K): infer R }
    ? R extends Xrm.Attributes.Attribute ? R : Xrm.Attributes.Attribute
    : Xrm.Attributes.Attribute;
  };

type ExtractControlMap<TForm, TFields extends string> =
  TForm extends { controls: infer C extends Record<string, Xrm.Controls.Control> } ? C :
  { [K in TFields]: TForm extends { getControl(name: K): infer R }
    ? R extends Xrm.Controls.Control ? R : Xrm.Controls.Control
    : Xrm.Controls.Control;
  };

type ExtractFormContext<TForm> =
  TForm extends { form: infer FC } ? FC :
  TForm extends Xrm.FormContext ? TForm :
  Xrm.FormContext;

// ─── TypedForm Type ──────────────────────────────────────────────────────────

/**
 * TypedForm: proxy type that maps field names to their attribute types.
 *
 * Provides direct property access to form fields (e.g. `form.name` returns
 * the StringAttribute), plus:
 * - `$context` for full FormContext access (ui, data, tabs, getAttribute with addOnChange)
 * - `controls.fieldName` for typed control access
 * - `$unsafe(name)` for off-form field access (fields loaded by D365 but not on the form)
 */
export type TypedForm<
  TForm,
  TFields extends string = ExtractFields<TForm>,
  TAttrMap extends Record<string, Xrm.Attributes.Attribute> = ExtractAttributeMap<TForm, TFields>,
  TCtrlMap extends Record<string, Xrm.Controls.Control> = ExtractControlMap<TForm, TFields>,
> = {
  /**
   * Direct field access: form.fieldName returns the typed Attribute.
   *
   * Non-nullable because the field is in the generated FormXml. If a field
   * is NOT in the generated interface, it won't compile, forcing you to use
   * $unsafe() which IS nullable. This is the compiler warning: a compile
   * error that says "this field is not on the form, use $unsafe()".
   */
  readonly [K in TFields]: K extends keyof TAttrMap
    ? TAttrMap[K]
    : Xrm.Attributes.Attribute;
} & {
  /** Access the underlying FormContext for ui, data, tabs, etc. */
  readonly $context: ExtractFormContext<TForm>;

  /**
   * Typed control access via form.controls.fieldname.
   *
   * Returns the specific control type from the generated ControlMap
   * (LookupControl, NumberControl, etc.). No cast needed.
   *
   * @example
   * ```typescript
   * form.controls.customerid.setEntityTypes([EntityNames.Account]);
   * form.controls.revenue.setVisible(false);
   * form.controls.name.setDisabled(true);
   * ```
   */
  readonly controls: {
    readonly [K in TFields]: K extends keyof TCtrlMap
      ? TCtrlMap[K]
      : Xrm.Controls.Control;
  };

  /**
   * Access an off-form field (loaded by D365 but not on the current form layout).
   * Returns null if the attribute does not exist.
   *
   * @example
   * ```typescript
   * form.$unsafe(OpportunityFields.VslBeauftragung)?.setValue(closeDate);
   * ```
   */
  $unsafe(name: string): Xrm.Attributes.Attribute | null;
};

/**
 * Wraps an Xrm Attribute so that setValue() automatically calls setSubmitMode('always').
 *
 * D365 AutoSave only submits "dirty" fields. Programmatically set values via setValue()
 * are NOT marked dirty by default, causing silent data loss on AutoSave. This proxy
 * intercepts setValue() and automatically marks the field for submission.
 *
 * This is intentionally invisible to the developer: they write `form.name.setValue('X')`
 * and the framework handles the rest. No more forgotten setSubmitMode calls.
 */
function wrapAttributeWithAutoSubmit(attr: Xrm.Attributes.Attribute): Xrm.Attributes.Attribute {
  return new Proxy(attr, {
    get(target, prop) {
      if (prop === 'setValue') {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Xrm.Attributes.Attribute.setValue has varying signatures per attribute type
        return (value: any) => {
          target.setValue(value);
          target.setSubmitMode('always');
        };
      }
      const val = (target as unknown as Record<string | symbol, unknown>)[prop];
      if (typeof val === 'function') return val.bind(target);
      return val;
    },
  });
}

/**
 * Create a typed form proxy around a FormContext.
 *
 * Pass the generated FormTypeInfo interface as type parameter (typegen >= 0.9.2).
 * It bundles the field/attribute/control maps so type extraction works across
 * package boundaries; the bare form interface resolves to `never` in consumer
 * projects (overload inference on getAttribute is unreliable across packages, TS 5.9+).
 *
 * @example
 * ```typescript
 * // Pass the generated <Form>TypeInfo type, not the bare form interface.
 * const form = typedForm<AccountLMFirmaFormTypeInfo>(ctx.getFormContext());
 * ```
 *
 * @param formContext - The Xrm.FormContext from executionContext.getFormContext()
 * @returns A proxy with direct typed property access to form fields
 */
export function typedForm<TForm>(
  formContext: Xrm.FormContext,
): TypedForm<TForm> {
  return createFormProxy(formContext) as TypedForm<TForm>;
}

/**
 * Internal: the field-access proxy shared by typedForm and typedFields.
 *
 * The runtime behaviour is IDENTICAL for both entry points; only the static type
 * differs (typedForm is non-nullable from a generated FormTypeInfo, typedFields
 * is nullable from a kindMap). Every string property resolves to the matching Xrm
 * attribute (wrapped so setValue() auto-submits); `$context`, `controls` and
 * `$unsafe` are the reserved escape hatches.
 */
function createFormProxy(formContext: Xrm.FormContext, nullOnMissingField = false): unknown {
  return new Proxy(formContext, {
    get(_target, prop) {
      if (typeof prop !== 'string') {
        return (formContext as unknown as Record<symbol, unknown>)[prop];
      }
      if (prop === '$context') return formContext;
      if (prop === 'controls') {
        return new Proxy({} as Record<string, Xrm.Controls.Control>, {
          get(_, controlName) {
            if (typeof controlName !== 'string') return undefined;
            return formContext.getControl(controlName);
          },
        });
      }
      if (prop === '$unsafe') {
        return (name: string) => formContext.getAttribute(name);
      }
      const attr = formContext.getAttribute(prop);
      if (attr) return wrapAttributeWithAutoSubmit(attr);
      // typedForm falls through to FormContext members (data, ui, ...); typedFields
      // treats a declared-but-absent field as honestly null (matches its `| null` type,
      // and its FormContext access goes through $context, not this fallthrough).
      return nullOnMissingField ? null : (formContext as unknown as Record<string, unknown>)[prop];
    },

    set(_target, prop, _value) {
      throw new TypeError(
        `Cannot assign to '${String(prop)}'. Call .setValue() on the field instead.`,
      );
    },

    has(_target, prop) {
      if (typeof prop !== 'string') return false;
      if (prop === '$context' || prop === 'controls' || prop === '$unsafe') return true;
      return formContext.getAttribute(prop) !== null;
    },
  });
}

// ─── TypedFields (cross-entity / multi-form via a kindMap) ───────────────────

/**
 * Attribute kind: a compact tag that maps a field to its Xrm.Attributes.* type.
 *
 * Used by {@link typedFields}, and emitted per entity as the generated
 * `XxxFieldKinds` constant by @xrmforge/typegen (>= the OE-16 release). The seven
 * kinds cover every standard Dataverse attribute type; the string literals here
 * are the contract typegen must emit.
 */
export type AttrKind =
  | 'string'
  | 'number'
  | 'boolean'
  | 'date'
  | 'optionset'
  | 'multiselect'
  | 'lookup';

/** Maps an {@link AttrKind} to its concrete Xrm.Attributes.* type. */
export interface KindToAttribute {
  string: Xrm.Attributes.StringAttribute;
  number: Xrm.Attributes.NumberAttribute;
  boolean: Xrm.Attributes.BooleanAttribute;
  date: Xrm.Attributes.DateAttribute;
  optionset: Xrm.Attributes.OptionSetAttribute;
  multiselect: Xrm.Attributes.MultiSelectOptionSetAttribute;
  lookup: Xrm.Attributes.LookupAttribute;
}

/** A kindMap: field logical name -> its {@link AttrKind}. */
export type KindMap = Record<string, AttrKind>;

/**
 * TypedFields: nullable, typed field access driven by a kindMap.
 *
 * Unlike {@link TypedForm} (non-nullable, one generated form), TypedFields is for
 * genuinely cross-entity or multi-form scripts: the same logic runs over records
 * that may or may not carry a given field, so every accessor is NULLABLE. This is
 * honest - a field absent on the current record is null, not a false non-null
 * (the OE-13 trap). It is the typed counterpart to the raw FormContext pattern.
 *
 * @typeParam M - the kindMap type (usually inferred from the argument)
 */
export type TypedFields<M extends KindMap> = {
  /** Direct field access: the nullable typed attribute (null if not on the record). */
  readonly [K in keyof M]: KindToAttribute[M[K]] | null;
} & {
  /** Access the underlying FormContext for ui, data, tabs, etc. */
  readonly $context: Xrm.FormContext;

  /**
   * Typed control access (nullable) via fields.controls.fieldname.
   *
   * Returns the primary control for the field, or null if absent. For a field
   * with multiple controls, reach every control via `fields.fieldname?.controls`
   * (the native Xrm.Attributes.Attribute.controls collection).
   */
  readonly controls: {
    readonly [K in keyof M]: Xrm.Controls.StandardControl | null;
  };

  /** Access a field not declared in the kindMap. Returns null if absent. */
  $unsafe(name: string): Xrm.Attributes.Attribute | null;
};

/**
 * Create a typed, NULLABLE field proxy from a kindMap (OE-16, Option B).
 *
 * For genuinely cross-entity or multi-form scripts where no single generated
 * `FormTypeInfo` fits (per AGENT.md these otherwise fall back to the raw
 * `Xrm.FormContext` pattern). The kindMap declares which fields to expose and
 * their kind; the proxy returns the matching Xrm attribute - NULLABLE, because a
 * field may be absent on the current record - with the same auto-submit wrapping
 * as {@link typedForm}. Pass the generated `XxxFieldKinds` constant (single entity
 * across several forms), or a hand-written map of named constants (a bespoke
 * cross-entity group).
 *
 * The kindMap argument drives TYPE inference and documents intent; the runtime
 * proxy resolves every access dynamically via getAttribute (identical to
 * typedForm), so the map's values are never read at runtime.
 *
 * @example
 * ```typescript
 * import { typedFields } from '@xrmforge/helpers';
 * import { QuotedetailFieldKinds } from '../generated/fields/quotedetail.js';
 *
 * // Single entity across several forms (nullable everywhere):
 * const f = typedFields(ctx.getFormContext(), QuotedetailFieldKinds);
 * f.quantity?.getValue();                 // number | null
 * f.quantity?.setValue(5);                 // auto-submits (setSubmitMode 'always')
 * f.controls.lm_einheittext?.setDisabled(true);
 *
 * // Bespoke cross-entity group (hand-written map of named constants):
 * const a = typedFields(fc, {
 *   [AddressFields.Line1]: 'string',
 *   [AddressFields.CountryId]: 'lookup',
 * } as const);
 * a[AddressFields.Line1]?.getValue();      // string | null
 * ```
 *
 * @param formContext - The Xrm.FormContext from executionContext.getFormContext()
 * @param kindMap - Maps each field's logical name to its AttrKind (type-only at runtime)
 * @returns A proxy with nullable, typed property access to the mapped fields
 */
export function typedFields<M extends KindMap>(
  formContext: Xrm.FormContext,
  kindMap: M,
): TypedFields<M> {
  // kindMap drives the static type only; the runtime proxy is dynamic (see typedForm).
  void kindMap;
  return createFormProxy(formContext, true) as TypedFields<M>;
}

/**
 * Typed, NULLABLE access to a SINGLE field addressed by a variable (non-literal)
 * field name. The single-field companion to {@link typedFields}.
 *
 * Use it when the field name is a runtime string (a parameter or config value) and a
 * two-kind kindMap would collapse to an attribute union: a kindMap built from
 * non-literal keys with two or more different kinds infers an index signature, so
 * every `f[param]` widens to the union of all kinds (F-LMA12-01). A single generic
 * `K` per call cannot collapse, so the returned attribute type stays exact.
 *
 * Returns the matching Xrm attribute (auto-submit-wrapped like typedForm/typedFields,
 * so setValue() marks the field dirty), or null if the field is absent on the current
 * record. This is a typed convenience over `getAttribute(name) as SomeAttribute` - the
 * `field` name is not statically checked against the entity (it is a runtime string),
 * so `kind` is an asserted tag, not a proof; its value is `typedField`, `null`-honesty
 * and auto-submit, not compile-time field validation.
 *
 * IMPORTANT: pass `kind` as a string LITERAL. If `kind` is an AttrKind-typed variable,
 * `K` widens to `AttrKind` and the return type becomes the union of all seven attribute
 * types. For several variable fields of different kinds, call typedField once per field
 * (not one mixed kindMap - that is exactly the F-LMA12-01 trap).
 *
 * @example
 * ```typescript
 * // Variable field names (named constants passed in), each exact and auto-submitting:
 * typedField(fc, flagField, 'boolean')?.getValue();          // boolean | null | undefined
 * typedField(fc, dateField, 'date')?.setValue(new Date());   // auto-submits
 * typedField(fc, userField, 'lookup')?.setValue([{ id, entityType, name }]);
 * ```
 *
 * @param formContext - The Xrm.FormContext from executionContext.getFormContext()
 * @param field - The field's logical name (a runtime string; not part of the return type)
 * @param kind - The attribute kind as a string LITERAL; drives the return type
 * @returns The typed attribute, or null if absent on the current record
 */
export function typedField<K extends AttrKind>(
  formContext: Xrm.FormContext,
  field: string,
  kind: K,
): KindToAttribute[K] | null {
  // kind drives the static type only; the attribute is resolved dynamically (like typedFields).
  void kind;
  const attr = formContext.getAttribute(field);
  return attr ? (wrapAttributeWithAutoSubmit(attr) as unknown as KindToAttribute[K]) : null;
}

// ─── normalizeGuid ───────────────────────────────────────────────────────────

/**
 * Normalize a GUID: strip curly braces and lowercase.
 *
 * Use this for GUIDs from sources other than formLookupId():
 * - `formContext.data.entity.getId()` returns GUIDs with braces
 * - WebApi `_value` fields may have braces depending on annotations
 * - Custom API responses may return GUIDs in varying formats
 *
 * formLookupId() already normalizes internally, so this is NOT needed for
 * lookup field access. Only use for getId(), WebApi responses, and comparisons.
 *
 * @param guid - A GUID string, possibly with braces and mixed case
 * @returns Normalized GUID (lowercase, no braces), or empty string if null/empty
 *
 * @example
 * ```typescript
 * const recordId = normalizeGuid(form.$context.data.entity.getId());
 * // "{A1B2C3D4-...}" -> "a1b2c3d4-..."
 *
 * const currencyId = normalizeGuid(result._transactioncurrencyid_value as string);
 * ```
 */
export function normalizeGuid(guid: string | null | undefined): string {
  if (!guid) return '';
  return guid.replace(/[{}]/g, '').toLowerCase();
}

/**
 * Whether the form's record is not yet persisted (Create form / unsaved).
 *
 * Treats BOTH "no id" representations as unsaved: an empty string (some Create
 * forms return `""` from `getId()`) and the null GUID
 * `00000000-0000-0000-0000-000000000000` (the other variant). Use this instead of
 * ad-hoc `getId() === ''` checks, which miss the null-GUID case (F-MK8-N4b).
 *
 * @param formContext - The form context (`executionContext.getFormContext()`)
 * @returns true if the record has no real id yet
 */
export function isUnsavedRecord(formContext: {
  data: { entity: { getId(): string } };
}): boolean {
  const id = normalizeGuid(formContext.data.entity.getId());
  return !id || id === '00000000-0000-0000-0000-000000000000';
}

// ─── Legacy Exports ──────────────────────────────────────────────────────────

/** @deprecated Use ExtractFields<TForm> instead */
export type FormFields<TForm> = ExtractFields<TForm>;
