/**
 * @xrmforge/helpers - TypedForm Proxy
 *
 * Creates a proxy around Xrm.FormContext that allows direct property access
 * to form fields. Instead of `form.getAttribute("name").setValue("X")`,
 * write `form.name.setValue("X")`.
 *
 * Works with generated form types from @xrmforge/typegen. Since v0.9.2,
 * typegen generates a `FormTypeInfo` interface per form that bundles
 * Fields, AttributeMap, and ControlMap for reliable type extraction.
 *
 * @example
 * ```typescript
 * import { typedForm } from '@xrmforge/helpers';
 * import type { AccountLMFirmaForm } from '../../generated/forms/account.js';
 *
 * const form = typedForm<AccountLMFirmaForm>(ctx.getFormContext());
 * form.name.getValue();           // string | null (typed)
 * form.revenue.setValue(150000);   // NumberAttribute (typed)
 * form.$context.ui.tabs.get(...); // Full FormContext access
 * form.controls.name;             // Control access (typed)
 * form.$unsafe('off_form_field');  // Access fields not on the form
 * ```
 */

// ─── FormTypeInfo Protocol ───────────────────────────────────────────────────

/**
 * Protocol interface generated by typegen for each form.
 * Bundles Fields, AttributeMap, and ControlMap so typedForm can extract
 * them reliably without fragile Conditional Type inference on overloads.
 *
 * Generated as: `export interface MyFormTypeInfo { fields: ...; attributes: ...; controls: ...; form: ...; }`
 */
export interface FormTypeInfoProtocol {
  fields: string;
  attributes: Record<string, Xrm.Attributes.Attribute>;
  controls: Record<string, Xrm.Controls.Control>;
  form: object;
}

// ─── Type Extraction ─────────────────────────────────────────────────────────

/**
 * Extract Fields from a Form interface.
 *
 * Strategy: Check if TForm has a companion TypeInfo interface (generated by
 * typegen >= 0.9.2). If so, extract fields directly. Otherwise, fall back
 * to Conditional Type inference on getAttribute (works in same compilation
 * unit but may fail across package boundaries in TS 5.9+).
 */
/**
 * Type extraction uses duck typing: if TForm has a `fields` property,
 * it's a TypeInfo interface (from typegen >= 0.10.0). Otherwise, fall
 * back to Conditional Type inference on getAttribute overloads.
 *
 * Duck typing (`TForm extends { fields: infer F }`) is more robust than
 * matching against FormTypeInfoProtocol because it doesn't require
 * structural compatibility of attributes/controls/form across packages.
 */
type ExtractFields<TForm> =
  TForm extends { fields: infer F extends string } ? F :
  TForm extends { getAttribute<K extends infer F>(name: K): unknown }
    ? F extends string ? F : never
    : never;

type ExtractAttributeMap<TForm, TFields extends string> =
  TForm extends { attributes: infer A extends Record<string, Xrm.Attributes.Attribute> } ? A :
  { [K in TFields]: TForm extends { getAttribute(name: K): infer R }
    ? R extends Xrm.Attributes.Attribute ? R : Xrm.Attributes.Attribute
    : Xrm.Attributes.Attribute;
  };

type ExtractControlMap<TForm, TFields extends string> =
  TForm extends { controls: infer C extends Record<string, Xrm.Controls.Control> } ? C :
  { [K in TFields]: TForm extends { getControl(name: K): infer R }
    ? R extends Xrm.Controls.Control ? R : Xrm.Controls.Control
    : Xrm.Controls.Control;
  };

type ExtractFormContext<TForm> =
  TForm extends { form: infer FC } ? FC :
  TForm extends Xrm.FormContext ? TForm :
  Xrm.FormContext;

// ─── TypedForm Type ──────────────────────────────────────────────────────────

/**
 * TypedForm: proxy type that maps field names to their attribute types.
 *
 * Provides direct property access to form fields (e.g. `form.name` returns
 * the StringAttribute), plus:
 * - `$context` for full FormContext access (ui, data, tabs, getAttribute with addOnChange)
 * - `controls.fieldName` for typed control access
 * - `$unsafe(name)` for off-form field access (fields loaded by D365 but not on the form)
 */
export type TypedForm<
  TForm,
  TFields extends string = ExtractFields<TForm>,
  TAttrMap extends Record<string, Xrm.Attributes.Attribute> = ExtractAttributeMap<TForm, TFields>,
  TCtrlMap extends Record<string, Xrm.Controls.Control> = ExtractControlMap<TForm, TFields>,
> = {
  /**
   * Direct field access: form.fieldName returns the typed Attribute.
   *
   * Non-nullable because the field is in the generated FormXml. If a field
   * is NOT in the generated interface, it won't compile, forcing you to use
   * $unsafe() which IS nullable. This is the compiler warning: a compile
   * error that says "this field is not on the form, use $unsafe()".
   */
  readonly [K in TFields]: K extends keyof TAttrMap
    ? TAttrMap[K]
    : Xrm.Attributes.Attribute;
} & {
  /** Access the underlying FormContext for ui, data, tabs, etc. */
  readonly $context: ExtractFormContext<TForm>;

  /**
   * Typed control access via form.controls.fieldname.
   *
   * Returns the specific control type from the generated ControlMap
   * (LookupControl, NumberControl, etc.). No cast needed.
   *
   * @example
   * ```typescript
   * form.controls.customerid.setEntityTypes([EntityNames.Account]);
   * form.controls.revenue.setVisible(false);
   * form.controls.name.setDisabled(true);
   * ```
   */
  readonly controls: {
    readonly [K in TFields]: K extends keyof TCtrlMap
      ? TCtrlMap[K]
      : Xrm.Controls.Control;
  };

  /**
   * Access an off-form field (loaded by D365 but not on the current form layout).
   * Returns null if the attribute does not exist.
   *
   * @example
   * ```typescript
   * form.$unsafe(OpportunityFields.VslBeauftragung)?.setValue(closeDate);
   * ```
   */
  $unsafe(name: string): Xrm.Attributes.Attribute | null;
};

/**
 * Wraps an Xrm Attribute so that setValue() automatically calls setSubmitMode('always').
 *
 * D365 AutoSave only submits "dirty" fields. Programmatically set values via setValue()
 * are NOT marked dirty by default, causing silent data loss on AutoSave. This proxy
 * intercepts setValue() and automatically marks the field for submission.
 *
 * This is intentionally invisible to the developer: they write `form.name.setValue('X')`
 * and the framework handles the rest. No more forgotten setSubmitMode calls.
 */
function wrapAttributeWithAutoSubmit(attr: Xrm.Attributes.Attribute): Xrm.Attributes.Attribute {
  return new Proxy(attr, {
    get(target, prop) {
      if (prop === 'setValue') {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Xrm.Attributes.Attribute.setValue has varying signatures per attribute type
        return (value: any) => {
          target.setValue(value);
          target.setSubmitMode('always');
        };
      }
      const val = (target as unknown as Record<string | symbol, unknown>)[prop];
      if (typeof val === 'function') return val.bind(target);
      return val;
    },
  });
}

/**
 * Create a typed form proxy around a FormContext.
 *
 * Accepts either a Form interface or a FormTypeInfo interface as type parameter.
 * When using FormTypeInfo (generated by typegen >= 0.9.2), type extraction is
 * guaranteed to work across all TypeScript versions.
 *
 * @example
 * ```typescript
 * // Recommended: use Form interface directly (requires typegen >= 0.9.2 for TypeInfo)
 * const form = typedForm<AccountLMFirmaForm>(ctx.getFormContext());
 *
 * // Alternative: use TypeInfo for explicit type extraction
 * const form = typedForm<AccountLMFirmaFormTypeInfo>(ctx.getFormContext());
 * ```
 *
 * @param formContext - The Xrm.FormContext from executionContext.getFormContext()
 * @returns A proxy with direct typed property access to form fields
 */
export function typedForm<TForm>(
  formContext: Xrm.FormContext,
): TypedForm<TForm> {
  return new Proxy(formContext as unknown as TypedForm<TForm>, {
    get(_target, prop) {
      if (typeof prop !== 'string') {
        return (formContext as unknown as Record<symbol, unknown>)[prop];
      }
      if (prop === '$context') return formContext;
      if (prop === 'controls') {
        return new Proxy({} as Record<string, Xrm.Controls.Control>, {
          get(_, controlName) {
            if (typeof controlName !== 'string') return undefined;
            return formContext.getControl(controlName);
          },
        });
      }
      if (prop === '$unsafe') {
        return (name: string) => formContext.getAttribute(name);
      }
      const attr = formContext.getAttribute(prop);
      if (attr) return wrapAttributeWithAutoSubmit(attr);
      return (formContext as unknown as Record<string, unknown>)[prop];
    },

    set(_target, prop, _value) {
      throw new TypeError(
        `Cannot assign to '${String(prop)}'. Use form.${String(prop)}.setValue() instead.`,
      );
    },

    has(_target, prop) {
      if (typeof prop !== 'string') return false;
      if (prop === '$context' || prop === 'controls' || prop === '$unsafe') return true;
      return formContext.getAttribute(prop) !== null;
    },
  });
}

// ─── normalizeGuid ───────────────────────────────────────────────────────────

/**
 * Normalize a GUID: strip curly braces and lowercase.
 *
 * Use this for GUIDs from sources other than formLookupId():
 * - `formContext.data.entity.getId()` returns GUIDs with braces
 * - WebApi `_value` fields may have braces depending on annotations
 * - Custom API responses may return GUIDs in varying formats
 *
 * formLookupId() already normalizes internally, so this is NOT needed for
 * lookup field access. Only use for getId(), WebApi responses, and comparisons.
 *
 * @param guid - A GUID string, possibly with braces and mixed case
 * @returns Normalized GUID (lowercase, no braces), or empty string if null/empty
 *
 * @example
 * ```typescript
 * const recordId = normalizeGuid(form.$context.data.entity.getId());
 * // "{A1B2C3D4-...}" -> "a1b2c3d4-..."
 *
 * const currencyId = normalizeGuid(result._transactioncurrencyid_value as string);
 * ```
 */
export function normalizeGuid(guid: string | null | undefined): string {
  if (!guid) return '';
  return guid.replace(/[{}]/g, '').toLowerCase();
}

// ─── Legacy Exports ──────────────────────────────────────────────────────────

/** @deprecated Use ExtractFields<TForm> instead */
export type FormFields<TForm> = ExtractFields<TForm>;
