/**
 * Example: Generate XrmForge types from a metadata fixture.
 *
 * This script demonstrates how @xrmforge/typegen generators work by processing
 * real Dataverse metadata (extracted from an Account entity) and producing flat
 * ESM .ts files - the same output a real `xrmforge generate` writes.
 *
 * Usage: npx tsx generate-from-fixture.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import {
  generateEntityInterface,
  generateEntityForms,
  generateEntityOptionSets,
} from '../../packages/typegen/src/generators/index.js';
import { parseForm } from '../../packages/typegen/src/metadata/form-parser.js';
import type {
  AttributeMetadata,
  LabelConfig,
  EntityTypeInfo,
} from '../../packages/typegen/src/metadata/types.js';

// ─── Load fixture ────────────────────────────────────────────────────────────

const fixtureRaw = readFileSync(join(__dirname, 'fixtures/account-metadata-fixture.json'), 'utf-8');
const fixture = JSON.parse(fixtureRaw);

const labelConfig: LabelConfig = {
  primaryLanguage: 1033,  // English
  secondaryLanguage: 1031, // German
};

// ─── Build EntityTypeInfo from fixture ───────────────────────────────────────

const attributes: AttributeMetadata[] = fixture.attributes;

const picklistAttributes = fixture.picklistAttributes.map((p: any) => ({
  ...attributes.find((a) => a.LogicalName === p.LogicalName)!,
  OptionSet: p.OptionSet,
  GlobalOptionSet: p.GlobalOptionSet,
}));

// Parse FormXml
const parsedForms = fixture.formXml
  ? [parseForm({
      name: 'Account',
      formid: 'standard-account-form',
      formxml: fixture.formXml,
      description: null,
      isdefault: true,
    })]
  : [];

const entityInfo: EntityTypeInfo = {
  entity: fixture.entity,
  attributes,
  picklistAttributes,
  lookupAttributes: attributes
    .filter((a) => a.AttributeType === 'Lookup' || a.AttributeType === 'Owner')
    .map((a) => ({ ...a, Targets: [] })),
  statusAttributes: [],
  stateAttributes: [],
  forms: parsedForms,
  oneToManyRelationships: [],
  manyToManyRelationships: [],
};

// ─── Generate (flat ESM .ts, matching `xrmforge generate`) ────────────────────

const HEADER = `// Generated by @xrmforge/typegen from real Dataverse metadata.
// Do not edit manually. Re-run generate-from-fixture.ts to update.

`;

const outDir = join(__dirname, 'generated');
mkdirSync(join(outDir, 'entities'), { recursive: true });
mkdirSync(join(outDir, 'optionsets'), { recursive: true });
mkdirSync(join(outDir, 'forms'), { recursive: true });

// 1. Entity Interface (for Web API response typing)
const entityContent = generateEntityInterface(entityInfo, { labelConfig });
writeFileSync(join(outDir, 'entities/account.ts'), HEADER + entityContent);
console.log('Generated: entities/account.ts');

// 2. OptionSet const enums
const optionSets = generateEntityOptionSets(
  fixture.picklistAttributes,
  'account',
  { labelConfig },
);
if (optionSets.length > 0) {
  const combinedOS = optionSets.map((os) => os.content).join('\n');
  writeFileSync(join(outDir, 'optionsets/account.ts'), HEADER + combinedOS);
  console.log(`Generated: optionsets/account.ts (${optionSets.length} enums)`);
}

// 3. Form interface(s) + Fields/Tabs/Sections enums
const formResults = generateEntityForms(
  parsedForms,
  'account',
  attributes,
  { labelConfig },
);
if (formResults.length > 0) {
  const combinedForms = formResults.map((f) => f.content).join('\n');
  writeFileSync(join(outDir, 'forms/account.ts'), HEADER + combinedForms);
  console.log(`Generated: forms/account.ts (${formResults.length} forms)`);
}

// 4. Barrel index (flat ESM re-exports, matching the generated barrel)
const indexContent = HEADER + [
  "export * from './entities/account.js';",
  "export * from './optionsets/account.js';",
  "export * from './forms/account.js';",
  '',
].join('\n');
writeFileSync(join(outDir, 'index.ts'), indexContent);
console.log('Generated: index.ts');

console.log('\nDone! Generated types are in ./generated/');
